list1 = ["apple", "banana", "orange"]
print(list1)
print(len(list1))
list1.append("grape")
print(list1)
print(len(list1))
list1.extend(["shaddock", "watermelon"])
print(list1)
print(len(list1))
list1.insert(0, "watermelon")
print(list1)
